import { type FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Input } from "../components/ui/Input";
import { isValidEmail } from "../lib/formValidation";
import { requestPasswordReset } from "../lib/passwordResetApi";

export function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setMessage("");
    setError("");

    const cleanEmail = email.trim().toLowerCase();

    if (!isValidEmail(cleanEmail)) {
      setError("Enter a valid email address.");
      return;
    }

    setIsSubmitting(true);

    try {
      const response = await requestPasswordReset({ email: cleanEmail });

      if (!response.ok) {
        setError(response.error.message);
        return;
      }

      setMessage(response.data.message);
    } catch (caughtError) {
      setError(caughtError instanceof Error ? caughtError.message : "Password reset request failed.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <main className="bg-slate-50">
      <section className="mx-auto grid min-h-[calc(100vh-145px)] max-w-5xl gap-8 px-6 py-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
        <div className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-sm lg:p-8">
          <div className="flex min-h-[24rem] flex-col justify-between rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
            <div className="inline-flex w-fit items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-sm font-semibold text-slate-200">
              <ShieldCheck className="h-4 w-4" />
              Account recovery
            </div>

            <div>
              <h1 className="text-4xl font-black tracking-tight">Reset safely</h1>
              <p className="mt-4 max-w-md text-sm leading-6 text-slate-300">
                Password reset links are generated by Apps Script and sent only when an active account can be verified.
              </p>
            </div>
          </div>
        </div>

        <Card className="mx-auto w-full max-w-md rounded-[2rem] p-6 lg:p-8">
          <h2 className="text-3xl font-bold tracking-tight text-ink">Reset your password</h2>
          <p className="mt-2 text-sm leading-6 text-muted">
            Enter your account email. If an active account exists, AGA LMS will send a one-time reset link.
          </p>

          <form onSubmit={handleSubmit} className="mt-6 space-y-5">
            <Input
              label="Email address"
              name="email"
              type="email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
              autoComplete="email"
              placeholder="you@example.com"
            />

            {error ? <Alert tone="error" message={error} /> : null}
            {message ? <Alert tone="success" message={message} /> : null}

            <Button type="submit" disabled={isSubmitting} className="w-full">
              <Mail className="h-4 w-4" />
              {isSubmitting ? "Sending..." : "Send reset link"}
            </Button>
          </form>

          <Link to="/login" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-slate-700 hover:text-slate-950">
            <ArrowLeft className="h-4 w-4" />
            Back to login
          </Link>
        </Card>
      </section>
    </main>
  );
}

function Alert({ tone, message }: { tone: "error" | "success"; message: string }) {
  const className =
    tone === "error"
      ? "rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700"
      : "rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700";

  return <div className={className}>{message}</div>;
}
